"""empty message

Revision ID: 6557113edfc2
Revises: 76878e690cb4
Create Date: 2022-11-11 16:23:33.340445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6557113edfc2'
down_revision = '76878e690cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('uid', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'uid')
    # ### end Alembic commands ###
