"""empty message

Revision ID: 8ac83895d2c0
Revises: 6557113edfc2
Create Date: 2022-11-11 16:39:37.057235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac83895d2c0'
down_revision = '6557113edfc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('uid', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
